# Generated by Django 4.2 on 2025-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spv', models.CharField(max_length=100)),
                ('voltage_level', models.CharField(max_length=20)),
                ('line_name', models.CharField(max_length=200)),
                ('criticality', models.CharField(max_length=20)),
                ('financial_year', models.CharField(max_length=20)),
                ('tower_span_no', models.CharField(max_length=100)),
                ('site_head', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('restoration_date', models.DateField()),
                ('restoration_time', models.TimeField()),
                ('total_time_hrs', models.FloatField()),
                ('outage_hrs', models.FloatField()),
                ('disturbance_type', models.CharField(max_length=100)),
                ('disturbance_category', models.CharField(max_length=100)),
                ('risk_factor', models.CharField(max_length=50)),
                ('total_line_length_kms', models.FloatField()),
                ('zone', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('Deemed', 'Deemed'), ('Technical', 'Technical')], max_length=20)),
                ('tripping_per_100ckt_km', models.FloatField()),
                ('fy_atl_ckt_km', models.FloatField()),
                ('per_100ckt_km', models.FloatField()),
                ('fy_atl_elements_count', models.IntegerField()),
                ('per_100ckt_km_elements_performance', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('line_criticality', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('asset_consideration_date', models.DateField()),
                ('asset_ageing_at_event', models.FloatField(help_text='Age in years at event')),
                ('asset_age_years', models.FloatField()),
                ('business_unit', models.CharField(max_length=100)),
                ('event_count', models.IntegerField()),
                ('ptw_availed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('ptw_returned', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('net_outage_hours', models.FloatField()),
                ('man_on_job', models.IntegerField(help_text='Man on job to attend disturbance')),
                ('manhours', models.FloatField()),
                ('vehicle_km', models.FloatField()),
                ('vehicle_cost', models.FloatField()),
                ('rm_cost', models.FloatField(help_text='Repair & Maintenance Cost')),
                ('transportation_cost', models.FloatField()),
                ('breakdown_cost', models.FloatField()),
                ('fy_week_no', models.IntegerField()),
            ],
        ),
    ]
