# Generated by Django 4.2 on 2025-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripping_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='fy_week_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='man_on_job',
            field=models.IntegerField(blank=True, help_text='Man on job to attend disturbance', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='net_outage_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='ptw_availed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='ptw_returned',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='risk_factor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='rm_cost',
            field=models.FloatField(blank=True, help_text='Repair & Maintenance Cost', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='transportation_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='tripping_per_100ckt_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
