# Generated by Django 4.2 on 2025-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripping_data', '0002_alter_incident_fy_week_no_alter_incident_man_on_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='fy_week_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
