# Generated by Django 4.2 on 2025-06-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripping_data', '0003_alter_incident_fy_week_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='breakdown_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='manhours',
            field=models.IntegerField(),
        ),
    ]
