# Generated by Django 4.2 on 2025-06-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripping_data', '0004_alter_incident_breakdown_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='total_time_hrs',
            field=models.TimeField(),
        ),
    ]
